/**
 * @file    main.c
 * @brief   Smart Rescue Boat — Main Entry Point
 * @author  Tejas Chandak
 * @date    2025
 *
 * System initialization and main control loop for the
 * autonomous rescue boat firmware running on STM32 Bluepill.
 */

#include "stm32f1xx_hal.h"
#include "navigation/navigation.h"
#include "detection/detection.h"
#include "communication/communication.h"
#include "power/power_mgmt.h"

/* ─── System Mode ───────────────────────────────────────────── */
typedef enum {
    MODE_AUTONOMOUS = 0,
    MODE_MANUAL,
    MODE_SEARCH,
    MODE_RETURN_TO_BASE
} SystemMode_t;

volatile SystemMode_t currentMode = MODE_AUTONOMOUS;

/* ─── Private Function Prototypes ───────────────────────────── */
static void SystemClock_Config(void);
static void GPIO_Init(void);
static void UART_Init(void);
static void run_autonomous_mode(void);
static void run_manual_mode(void);
static void run_search_mode(void);

/* ─────────────────────────────────────────────────────────── */

int main(void)
{
    /* HAL and system clock init */
    HAL_Init();
    SystemClock_Config();

    /* Peripheral init */
    GPIO_Init();
    UART_Init();

    /* Module init */
    Navigation_Init();
    Detection_Init();
    Communication_Init();
    PowerMgmt_Init();

    /* Brief startup delay */
    HAL_Delay(500);

    /* ── Main Control Loop ── */
    while (1)
    {
        /* Check for incoming commands (Wi-Fi / Bluetooth) */
        Communication_ProcessIncoming(&currentMode);

        /* Check battery level — force return if critical */
        if (PowerMgmt_IsBatteryCritical()) {
            currentMode = MODE_RETURN_TO_BASE;
        }

        /* Execute current operating mode */
        switch (currentMode)
        {
            case MODE_AUTONOMOUS:
                run_autonomous_mode();
                break;

            case MODE_MANUAL:
                run_manual_mode();
                break;

            case MODE_SEARCH:
                run_search_mode();
                break;

            case MODE_RETURN_TO_BASE:
                Navigation_ReturnToBase();
                break;

            default:
                currentMode = MODE_AUTONOMOUS;
                break;
        }

        HAL_Delay(50); /* 20 Hz main loop */
    }
}

/* ─── Mode Handlers ─────────────────────────────────────────── */

/**
 * @brief Autonomous mode: obstacle avoidance + victim search
 */
static void run_autonomous_mode(void)
{
    uint16_t obstacle_dist = Detection_GetObstacleDistance();

    if (obstacle_dist < OBSTACLE_THRESHOLD_CM) {
        Navigation_AvoidObstacle(obstacle_dist);
    } else {
        Navigation_MoveForward();
    }

    if (Detection_IsVictimDetected()) {
        currentMode = MODE_SEARCH;
    }
}

/**
 * @brief Manual mode: relay incoming directional commands to motors
 */
static void run_manual_mode(void)
{
    DriveCommand_t cmd = Communication_GetLastCommand();
    Navigation_ExecuteCommand(cmd);
}

/**
 * @brief Search mode: slow patrol around detected victim location
 */
static void run_search_mode(void)
{
    Navigation_SlowPatrol();
    Communication_SendAlert(ALERT_VICTIM_FOUND);

    /* Exit search mode after alert is sent and boat holds position */
    if (Communication_IsAlertAcknowledged()) {
        Navigation_HoldPosition();
    }
}

/* ─── System Init Stubs ─────────────────────────────────────── */

static void SystemClock_Config(void)
{
    /* TODO: Configure system clock to 72 MHz via PLL
     *       Source: HSE 8 MHz crystal on Bluepill
     *       Generated by STM32CubeMX — paste config here */
}

static void GPIO_Init(void)
{
    /* TODO: Configure GPIO pins for:
     *   - Motor PWM outputs  (PA0, PA1, PA2, PA3)
     *   - Ultrasonic trigger/echo (PB0, PB1)
     *   - IR sensor input   (PB5)
     *   - Status LED        (PC13 — onboard) */
}

static void UART_Init(void)
{
    /* TODO: Configure UART1 (PA9/PA10) for ESP8266 — 115200 baud
     *       Configure UART2 (PA2/PA3) for HC-05  —   9600 baud */
}
